# Generated by Django 5.0.2 on 2025-03-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('description', models.TextField()),
                ('experience', models.IntegerField(default=0)),
                ('education', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', '-created_at'],
            },
        ),
    ]
