export const EMERGENCY_LIST_REQUEST = 'EMERGENCY_LIST_REQUEST';
export const EMERGENCY_LIST_SUCCESS = 'EMERGENCY_LIST_SUCCESS';
export const EMERGENCY_LIST_FAIL = 'EMERGENCY_LIST_FAIL';

export const EMERGENCY_CREATE_REQUEST = 'EMERGENCY_CREATE_REQUEST';
export const EMERGENCY_CREATE_SUCCESS = 'EMERGENCY_CREATE_SUCCESS';
export const EMERGENCY_CREATE_FAIL = 'EMERGENCY_CREATE_FAIL';

export const EMERGENCY_UPDATE_REQUEST = 'EMERGENCY_UPDATE_REQUEST';
export const EMERGENCY_UPDATE_SUCCESS = 'EMERGENCY_UPDATE_SUCCESS';
export const EMERGENCY_UPDATE_FAIL = 'EMERGENCY_UPDATE_FAIL'; 